name: gaskeun
services:
  # ==================== PostgreSQL ====================
  postgres:
    image: postgres:16
    container_name: gaskeun-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gaskeun
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gaskeun_booking
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  # ==================== Redis ====================
  redis:
    image: redis:7
    container_name: gaskeun-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # ==================== MongoDB ====================
  mongodb:
    image: mongo:7
    container_name: gaskeun-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ==================== Kafka (KRaft) ====================
  kafka:
    image: bitnami/kafka:4.0
    container_name: gaskeun-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka

  # ==================== Kafka UI ====================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: gaskeun-kafka-ui
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: gaskeun_kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
    depends_on:
      - kafka
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  pg-data:
  redis-data:
  mongo-data:
  kafka-data:
