version: '3.8'

name: gaskeun
services:
  # ==================== PostgreSQL ====================
  postgres:
    image: postgres:16
    container_name: gaskeun-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gaskeun
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gaskeun_booking
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  # ==================== Redis ====================
  redis:
    image: redis:7
    container_name: gaskeun-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # ==================== MongoDB ====================
  mongodb:
    image: mongo:7
    container_name: gaskeun-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ==================== Kafka (KRaft) ====================
  kafka:
    image: apache/kafka:4.0.0
    container_name: gaskeun-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # Kafka client
      - "9093:9093"   # Kafka controller (internal)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: "gaskeun-cluster-id"
    volumes:
      - kafka-data:/var/lib/kafka/data

  # ==================== Kafka UI ====================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: gaskeun-kafka-ui
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: gaskeun
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""
    depends_on:
      - kafka

volumes:
  pg-data:
  redis-data:
  mongo-data:
  kafka-data:
